### ISSUE TITLE
Marc21 indicators: Check allowed indicators to become compliant with LOC

### ISSUE THREAD

**Issue by Kennethhole** [inveniosoftware/dojson#22]
Hi,
I recognized that the allowed indicators for 245 is not correct.
https://github.com/inveniosoftware/dojson/blob/master/dojson/contrib/marc21/fields/bd20x24x.py#L186
Here, the second indicator should allow character 0,1,2,3,4,5,6,7,8,9.
http://www.loc.gov/marc/bibliographic/bd245.html

I believe the automatic extraction of which indicators that are allowed has failed due to the use of "1-9".
If you have a look at "Varying form of the title", it is correct since all the numbers are listed at the LOC website. 
https://github.com/inveniosoftware/dojson/blob/master/dojson/contrib/marc21/fields/bd20x24x.py#L226
http://www.loc.gov/marc/bibliographic/bd246.html

I quickly had a look, and it seems like we have the same problem with 222, 240, 242 and 243 as well. This is only for titles, and we should have a look at the other MARC fields as well.

**Comment by fjorba** [comment]
I have been asking for years (literally) that Invenio should accept any indicator as valid (see #19, for example, or https://github.com/inveniosoftware/invenio/issues/1722).  I'm also asking that Invenio should accept to repeat fields or subfields (see #23).  I thought that we reached an agreement about it already (not so about  repetitive vs non-repetitive fields, still open).

I won't repeat my arguments, except the Postel principle: Be conservative in what you do, be liberal in what you accept from others.

**Comment by fjorba** [comment]
Another argument is that Marc21 allows 9 as a local valid indicator, for any indicator, for any tag.

**Comment by tiborsimko** [comment]
> Another argument is that Marc21 allows 9 as a local valid indicator, for any indicator, for any tag.

Is that so?  If yes, then one could override the meaning of 24519 which has otherwise fixed meaning of "nine nonfiling characters" according to [MARC21 field 245 documentation](http://www.loc.gov/marc/bibliographic/bd245.html).  Wouldn't overriding this mean to go against the standard?

Anyway, this is all about setting appropriate values in expressions like:

```
@marc21.over('title_statement', '^245[10_][0_]')
@marc21.over('varying_form_of_title', '^246[1032_][_103254768]')
```

The first line should have basically any number from 0 to 9 allowed for the second indicator in 245, but the script that generates this did not probably recognise "1-9" properly, hence not retained them.
