### ISSUE TITLE
Create demosite with Records and Search modules

### ISSUE THREAD

**Issue by switowski** [inveniosoftware/dojson#80]
Should we reuse invenio-demosite package ?
What would be the easiest way to have 'easy to install' demosite package ?

**Comment by switowski** [comment]
As discussed with @tiborsimko , the best option is to create demosite inside invenio-marc21 package with a simple script to create demorecords (reuse the existing invenio scripts).

**Comment by tiborsimko** [comment]
The separate `invenio-demosite` package had better be disposed of for Invenio 3 matters.  The demo site integration can be done inside `invenio` package, as is the case now.  If people install `invenio-marc21`, then they would simply have proper JSON Schema support, proper Elasticsearch mapping, and proper record templates installed so that their site would look nice.  (The "nice defaults" idea.)

(BTW, this issue does not really belong to the `dojson` repository; rather to the `invenio` repository.)

**Comment by switowski** [comment]
As @hachreak is already working on demo app in https://github.com/inveniosoftware/invenio-marc21 (with templates and possibly working search), I think we can close this issue.
