### ISSUE TITLE
RFC: One big metadata MARC21 file for testing ?

### ISSUE THREAD

**Issue by switowski** [inveniosoftware/dojson#83]
Hi,

@tiborsimko , @lnielsen, @egabancho during this sprint, we have gathered some example metadata from Zenodo, TIND and CDS. Do you think it makes sense to combine them in a one big record with all possible MARC21 fields (also including tags from those 6 records provided by @Kennethhole in https://github.com/inveniosoftware/dojson/pull/76/files) ?
Or should we create separate files for each source (`cds_demo_data.xml`, `zenodo_demo_data.xml`, `tind_demo_data.xml`) ?
Or should we create one big file with multiple records inside ?
The main reason for that is the maintainability of data in the future (we can easily add new fields if we keep only one file with test data).

**Comment by tiborsimko** [comment]
What about having a folder with separate MARC test files testing separate things? E.g. a canonical example MARC record from LoC http://www.loc.gov/standards/marcxml/xml/collection.xml,  another canonical example of a book record or a video record, another example of a record with "interesting" subfield order that Tind found, etc.  In this way it'll be easier to maintain the test suite and enrich it in the future should a service come up with a "real life" example that is conform to MARC cataloguing practices in the given country but not passing our JSON transformations due to a bug or something.

**Comment by switowski** [comment]
Hmm, strange, I thought I have answered here but my comment disappeared :(
I agree with you, it makes more sense to keep separate files if we want to test different use cases. I'm closing this issue.
